services:
  - type: web
    name: bengkel-autocare
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn bengkel.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bengkel-db
          property: connectionString

databases:
  - name: bengkel-db
    plan: free
    region: singapore
    databaseName: bengkel_db
    user: bengkel_user
    ipAllowList: []
